### ISSUE TITLE
"Prettier syncing config" on every newline in org-babel js source block

### ISSUE THREAD

**Issue by bi1yeu** [jscheid/prettier.el#100]
**Describe the bug**

Hi! I'm using Org Babel with a JavaScript code block like this:

```
#+begin_src js
console.log("Hello, World!");
#+end_src
```

Whenever I create a new line inside the source code block, the message "Prettier syncing config" appears in the minibuffer, and Emacs hangs for a moment. I don't know if this is a bug, per se, or even whether it's something than can be fixed by prettier.el, but it's impeding my workflow so I figured I'd ask. Any advice is appreciated, thanks in advance!

**Link to `M-x prettier-info` output**
We suggest you copy the output into a [Gist](https://gist.github.com/) after sanitizing it. Make sure to run `prettier-info` in the buffer where you experienced the problem. If possible, include a copy of that buffer's contents in the Gist.

[prettier-info.el](https://gist.github.com/bi1yeu/e8023f758ead659855ea37b0f61f4a39)

**To Reproduce**
1. open a scratch buffer in org-mode
1. create a js source code block
1. put cursor inside code block and press Enter key
1. observe the "Prettier syncing config" message

**Expected behavior**

I'd expect prettier config to sync only once (I think?)

**Additional context**

I'm using [doom-emacs](https://github.com/hlissner/doom-emacs).

**Comment by jscheid** [comment]
Hi, I can reproduce this. I'll have a look to see what can be done about it.

I'm wondering, does this package otherwise work alongside org-mode as you'd expect?

**Comment by bi1yeu** [comment]
I'm not a heavy user of either mode, but I only recently installed prettier and noticed this issue.

Upon further investigation, it does not look like the JavaScript code inside of the Org source code block is being formatted by prettier when the buffer is saved. E.g., I put `console.log( "Hello, World");` in a source code block and it's not reformatted. The same code in a js-mode buffer is reformatted as expected.

**Comment by jscheid** [comment]
This should be fixed in the latest release.

I've also added an (experimental) function `prettier-prettify-org-src-code-at-point`. I might build this out into something more fully featured at a later point, perhaps spun out into its own package. If you are going to use it I'd be keen to hear how you go with it.
