### ISSUE TITLE
prettier runs on buffer save after pretttier-mode is disabled

### ISSUE THREAD

**Issue by dsana123** [jscheid/prettier.el#106]
**Describe the bug**
When I disable prettier-mode and then save the buffer, prettier still runs on buffer save

**Link to `M-x prettier-info` output**
https://gist.github.com/dsana123/6ef6db18009a2d357662d15a6cf63b3d

**To Reproduce**
- Create an init.el file
```
(setq package-list '( prettier ))
(package-initialize)
```

- Start emacs
```
emacs -Q --load init.el test.js
```

- Enable prettier-mode, and check it is enabled
```
M-x prettier-mode
```

- Disable prettier-mode, and check it is disabled
```
M-x prettier-mode
```

- Edit test.js
- Save test.js
-  Check that prettier has run on the test.js file

**Expected behavior**
I expect that prettier should not run on buffer save

**Additional context**
- I am running on Arch Linux with package `emacs-nox 28.1-7`
- Prettier package info
```
Package prettier is installed.

     Status: Installed in ‘prettier-20220526.703/’ (unsigned). [Delete]
    Version: 20220526.703
     Commit: f52712b14a9223a6168635c48e87d31304d3e3ae
    Summary: Code formatting with Prettier
   Requires: emacs-26.1, iter2-0.9, nvm-0.2
    Website: https://github.com/jscheid/prettier.el
   Keywords: [convenience] [languages] [files]
 Maintainer: Julian Scheid <julians37@gmail.com>
     Author: Julian Scheid <julians37@gmail.com>
```
- My workaround is to modify the `prettier-prettify-on-save-flag` variable to prevent prettier running on buffer save if prettier-mode is disabled

**Comment by dsana123** [comment]
I have tested the latest release that was pushed to MELPA (details below), and it fixes the issue.  This PR fixed the issue: https://github.com/jscheid/prettier.el/pull/107

```
Package prettier is installed.

     Status: Installed in ‘prettier-20220530.1042/’ (unsigned). [Delete]
    Version: 20220530.1042
     Commit: 5c0304876b68a4faf125a039451098bd448a49bf
    Summary: Code formatting with Prettier
   Requires: emacs-26.1, iter2-0.9, nvm-0.2
    Website: https://github.com/jscheid/prettier.el
   Keywords: [convenience] [languages] [files]
 Maintainer: Julian Scheid <julians37@gmail.com>
     Author: Julian Scheid <julians37@gmail.com>
Other versions: 20220530.1042 (melpa), 1.2.0 (melpa-stable).
```

**Comment by jscheid** [comment]
Thanks for the report!
