### ISSUE TITLE
Sometimes prettier-version does not follow

### ISSUE THREAD

**Issue by ncaq** [jscheid/prettier.el#117]
**Describe the bug**
Sometimes prettier-version does not follow, causing a parse error and requiring an explicit prettier-restart.

**Link to `M-x prettier-info` output**
I am very sorry, but when I ran it, it contained confidential information and I cannot paste it.
If you must, I will create a minimum reproduction environment and paste it back in.

**To Reproduce**
After looking at the prettier target files in the master branch, etc., move to a branch with a different version of prettier and follow the prettier changes with npm install, yarn install, etc.

**Expected behavior**
prettier-version is correctly updated and the correct version of prettier is executed.

**Additional context**
For example, the following error may occur

~~~
SyntaxError: ',' expected. (164:31)
  162 |         });
  163 |       default:
> 164 |         throw new Error(stage satisfies never);
      |                               ^
  165 |     }
  166 |   }
  167 | }
~~~

**Comment by jscheid** [comment]
Yes, this is a known issue described [here](https://github.com/jscheid/prettier.el#changing-prettier-configuration).

You're right that it would be nice for this to work automatically but it's a lot of work for something that bothers me very rarely. Too much work for me I'm afraid, but a PR would be welcome.

**Comment by ncaq** [comment]
Oops, I thought I had searched for the issue, but I did not read all the documentation.
My apologies.

**Comment by jscheid** [comment]
No problem at all!
