### ISSUE TITLE
Prettier fails to find config and times out after upgrade to latest version

### ISSUE THREAD

**Issue by cmatzenbach** [jscheid/prettier.el#132]
**Describe the bug**
First off, wanted to say thank you so much for this package, it is the lifeblood of my workflow.  However, today I updated all my emacs packages (including the lsp language servers, not sure if that matters or not), and after restarting, the package no longer works and I keep getting the error `Could not sync Prettier config, consider setting ‘prettier-mode-sync-config-flag’ to nil: (error "Prettier timed out after 20 seconds")`.  For a bit of background - the repo I work in daily uses nvm, which is locked in to node 12.16.1.  The repo also has prettier installed as a dependency in `node_modules` and has a `.prettierrc.json` in the project root (all the contributors use prettier).  I have put the link to my prettier-info gist below.

I read through the readme several times, and saw that this extension is looking for node in the `exec-path`, which after analyzing I realized it was not present (I am not sure if it was present before and was removed after the upgrade; I never had explicitly set the `exec-path` to my project's node version in my `init.el`, so I am not sure how it found it before).  Regardless I manually set it after troubleshooting (as you will see in the gist), but that did not solve the problem either.  For reference:

```
matzy at omnisci in ~/Projects/immerse (master●) 
$ node --version
v12.16.1

matzy at omnisci in ~/Projects/immerse (master●) 
$ which node
/home/matzy/.nvm/versions/node/v12.16.1/bin/node
 
matzy at omnisci in ~/Projects/immerse (master●) 
$ npm list prettier
immerse@7.2.0-dev /home/matzy/Projects/immerse
└── prettier@2.0.5 
```

Relevant entry in `init.el`:
```
(setq exec-path (append exec-path '("/home/matzy/.nvm/versions/node/v12.16.1/bin/node")))
```

In case it helps, the projects `.prettierrc.json` file:
```
{
  "arrowParens": "always",
  "endOfLine": "lf",
  "jsxSingleQuote": false,
  "semi": false,
  "singleQuote": false,
  "trailingComma": "none",
  "overrides": [
    {
      "files": "*.json",
      "options": {
        "parser": "json"
      }
    }
  ]
}
```

**Link to `M-x prettier-info` output**
[Gist](https://gist.github.com/cmatzenbach/e2fbe6e5878d2ed3bf7b6df499ddfa7e)

**To Reproduce**
Open a typescript/javascript/etc file in my project, enable `prettier-mode`.

**Expected behavior**
`prettier-mode` should startup without errors and format my buffer on save as usual.

**Additional context**
I was wondering, does this have any relation to lsp/the lsp language servers being used for a given project?  I was trying to figure out if updating lsp and the servers could somehow have been involved, and tried to play around with disabling lsp and such, but never had any success.  I would assume there isn't any interaction though, as lsp isn't a dep for this package.

I read through both the elisp and js code, but I don't know how to debug elisp and wasn't sure when the js code is triggered and how to capture console logs from it to try and determine the issue.  This package is a lifesaver for me, so I am more than willing to help with any debugging to help fix the issue if you can instruct me how to do so.  To be honest, if my elisp ever gets better, I would even love to help maintain/contribute to it, that's how much of a lifesaver this package has been for me :)

Thank you!

**Comment by jscheid** [comment]
Also thanks for the kind words, I'm glad it's useful to you!

**Comment by jscheid** [comment]
Hmm, interesting. It might be the node process crashing. Please set `prettier-keep-server-buffer-flag` to a truthy value and try again?

**Comment by cmatzenbach** [comment]
Ok that does prevent that buffer from crashing, but it still is blank, even after saving.

**Comment by jscheid** [comment]
From memory we're never killing the process except on user request (i.e. `prettier-restart`.) So this would mean something else is killing the process, either inside Emacs (a package that's a bit trigger happy with `kill-process` perhaps) or outside (the OOM killer maybe) -- or it crashes. If it's not `kill-process` I'd expect [this](https://github.com/jscheid/prettier.el/blob/d11bd504bb485d921e287b43bd5571469f28c40f/prettier.el#L933) to get triggered, is it?

It would be good to rule out interference from another package, could you try loading just this package alone in an otherwise vanilla Emacs and see if it still breaks?

**Comment by cmatzenbach** [comment]
Hey what do you know!  I updated all my packages just now, and it works again!  No idea what happened, but all good now.

Vielen dank fuer ihre hilfe, gruesse aus der Staaten!  😄

**Comment by jscheid** [comment]
Ha, ok then 🤷 all the better, glad it works now. Gruß zurück!
