### ISSUE TITLE
Configure a plugin

### ISSUE THREAD

**Issue by bodnarlajos** [jscheid/prettier.el#141]
Hi,
First of all thanks for your work ! it is a good mode for emacs!
My question is that how I can configure the sql plugin for prettier correctly ?
I can run this command line to format my sql file:
"npx prettier --plugin=prettier-plugin-sql projects/db.sql"
The  prettier-info don't listing this plugin ... 
The sql plugin is installed to the $HOME/node_modules.
I tried to create the .prettierrc with this content:
```
{
  "plugins": ["prettier-plugin-sql"]
}
```
With this .prettierrc config in the project folder is resulting that there is no plugins for prettier (like an unconfigured one)...
How I can configure the plugins for this mode ?
Thanks in advance!

**Comment by jscheid** [comment]
That should work. I'm using it myself with `@prettier/plugin-ruby` in the same way (with a `.prettierrc` that looks similar to yours.)

Can you share output of `M-x prettier-info`, running it in a buffer where you'd expect it to work?

**Comment by bodnarlajos** [comment]
It was my fault! I didn't configure the node with nvm correctly... 
It is working as expected! 
Thanks!

**Comment by jscheid** [comment]
No problem, glad it works now and that you find it useful.
