### ISSUE TITLE
file-missing "Opening input file" "No such file or directory" prettier-el.js.gz.base64

### ISSUE THREAD

**Issue by Sleepful** [jscheid/prettier.el#38]
**Describe the bug**
It doesn't prettify, I am getting "no such file of directory".

**Link to `M-x prettier-info` output**

https://gist.github.com/Sleepful/141dc007e93bdf6a06bacb315e60afd8

here is the part:
```
 :prettier-options
                (file-missing "Opening input file" "No such file or directory" "/Users/user/.emacs.d/.local/straight/build-28.0.50/prettier/prettier-el.js.gz.base64")
```

**To Reproduce**
`M-x prettier-prettify` or saving the file, errors out. I'm using NVM, and straight package manager for emacs

**Additional context**
I'm on a mac

output of `ls /Users/user/.emacs.d/.local/straight/build-28.0.50/prettier`:
```
bootstrap.js		prettier-autoloads.el	prettier.el
externs.js		prettier-el.js		prettier.elc
```

**Comment by jscheid** [comment]
Are you using latest `straight.el`?

See https://github.com/raxod502/straight.el/issues/621#issuecomment-716576438

**Comment by jscheid** [comment]
Haven't heard back from you, I'll assume upgrading `straight.el` will fix your issue. Let me know if this doesn't work for some reason.

**Comment by Sleepful** [comment]
Just saw this, yes! Thank you very much.
