### ISSUE TITLE
(defvar prettier-parser-history nil) ?

### ISSUE THREAD

**Issue by xuchunyang** [jscheid/prettier.el#59]
With helm-mode is on, C-u prettier-prettify does not work and complains prettier-parser-history is not defined. With vanilla Emacs completion, this seems not an issue, I just learnt Emacs'll define the variable automatically. In my past impression, authors define the history variable explicitly.

**Comment by jscheid** [comment]
@xuchunyang thanks, #60 should fix both issues you've reported.

Could you install the tarball for that PR and see if it works? You can download it [here](https://github.com/jscheid/prettier.el/suites/1659551110/artifacts/30843085) (unzip the zip file but don't untar the tarball.)

**Comment by xuchunyang** [comment]
It works.
