### ISSUE TITLE
Hangs with output C-1

### ISSUE THREAD

**Issue by jscheid** [jscheid/prettier.el#62]
Prettier.el can get into a broken state sometimes, where all operations hang. This is what's in `*prettier (local)*`.

```
C-1
Z0
```

I think the problem here is that `result["cursorOffset"]` can be negative which then breaks the response parsing in `prettier.el`. We should probably ignore negative offsets and not send the `C` line at all.

I haven't been able to reproduce this reliably so far, but it did happen a couple of times to me, once in a `tsconfig.json` file and once in a Java source file.

**Comment by MarcusRiemer** [comment]
Thanks for fixing this, I just stumbled over the problem yesterday and wanted to open an issue. I can confirm that this fix works for me as well.
