### ISSUE TITLE
Default configuration

### ISSUE THREAD

**Issue by Sleepful** [jscheid/prettier.el#76]
I like to write the occasional .js script, prettier formats it with the default options

I'd like the ability to define default options when no configuration file is found. Similar to https://github.com/prettier/prettier-emacs#prettier-arguments

**Comment by jscheid** [comment]
You can put a [configuration file](https://prettier.io/docs/en/configuration.html) somewhere high up in your FS hierarchy, maybe in your home directory. It will affect all files in that directory and sub-directories. Does that work?

**Comment by jscheid** [comment]
I'm going to close this, assuming that the above will let you do what you're after. The ability to specify settings somewhere they won't be picked up when Prettier is run in some other way (e.g. on the command line or in another editor (lol)) is an anti-feature in my opinion.
