### ISSUE TITLE
Package I installed from melpa didn't come with info

### ISSUE THREAD

**Issue by dabrahams** [jscheid/prettier.el#79]
**Describe the bug**
The customize-group contains a reference to the info node: `(prettier)prettier-editorconfig-flag' but when I installed the package I didn't get any info for prettier AFAICT.  When I follow the link, I get "user-error: Info file prettier does not exist"

**Comment by jscheid** [comment]
Thanks, yes it's not in https://github.com/jscheid/prettier.el/tree/release so that would be why.
