### ISSUE TITLE
file-missing "Opening input file" "No such file or directory" prettier-el.js.gz.base64

### ISSUE THREAD

**Issue by alecvn** [jscheid/prettier.el#90]
I am getting this error when I do `M-x prettier-info`.  Unlike the previous issue created under this header, I am _not_ using the `straight` package.

```
(file-missing "Opening input file" "No such file or directory" "~/.emacs.d/elpa/prettier-20210606.1150/prettier-el.js.gz.base64")
```

**Comment by jscheid** [comment]
Thanks for bringing this to my attention. As far as I can tell this is an issue with MELPA, I've opened a ticket over there: https://github.com/melpa/melpa/issues/7652

**Comment by jscheid** [comment]
As a workaround you could install directly from this tarball: https://github.com/jscheid/prettier.el/suites/2922863809/artifacts/65601677

You'd need to unzip it (not untar it) and then use `M-x package-install-file`

**Comment by alecvn** [comment]
I assumed it was a MELPA issue but just wanted to check here first.

I'll try your suggested workaround, thanks!

**Comment by alecvn** [comment]
@jscheid sorry to drag this on, but I get ```(error "Package lacks a file header")``` when I try to install from that tarball.

**Comment by jscheid** [comment]
No problem. Did you unzip it? You should have a tarball that looks like this:

```
$ file prettier-20210606.1150.tar
prettier-20210606.1150.tar: POSIX tar archive (GNU)

$ tar tf prettier-20210606.1150.tar 
prettier-20210606.1150/
prettier-20210606.1150/prettier-el.js
prettier-20210606.1150/prettier.el
prettier-20210606.1150/prettier-pkg.el
prettier-20210606.1150/externs.js
prettier-20210606.1150/bootstrap.js
```

Then, in Emacs `M-x package-install-file RET /path/to/prettier-20210606.1150.tar RET` should work.

**Comment by alecvn** [comment]
Okay that was silly of me.  Got it.

For anyone reading this later, I just needed to restart Emacs (restarting `prettier` didn't work) so that it wasn't trying to look for the elpa version of `prettier`.

@jscheid feel free to close this issue if you'd rather Melpa track it, thank you very much for your assistance.

**Comment by jscheid** [comment]
Glad I could help. I might leave it open until this is sorted.

**Comment by rieje** [comment]
> As a workaround you could install directly from this tarball: https://github.com/jscheid/prettier.el/suites/2922863809/artifacts/65601677
> 
> You'd need to unzip it (not untar it) and then use `M-x package-install-file`

@jscheid Sorry, can you provide an updated link? I am having the same issue but this link leads to a 404 page. Thanks.

**Comment by jscheid** [comment]
Ah weird, the link works for me... anyway, attaching it here: [prettier.tar.zip](https://github.com/jscheid/prettier.el/files/6866648/prettier.tar.zip)

GitHub won't let me attach it unzipped so you'll still have to do that.

**Comment by gavinpc-mindgrub** [comment]
I ran into this as well, seemingly out of nowhere.  Prettier was doing bizarre things, like putting random space all over certain files.

The end of `prettier-info`'s output looked like this

```
  :prettier-options
  (file-missing "Opening input file" "No such file or directory" "/Users/GCannizzaro/.emacs.d/elpa/prettier-20210606.1150/prettier-el.js.gz.base64"))
```

There appeared to be a discrepancy between the package directory contents and the code's expectations.  The contents of the directory were

```
    -rw-r--r--  1526 07-19 14:35 bootstrap.js
    -rw-r--r--  1643 07-19 14:35 externs.js
    -rw-r--r--  2620 07-19 14:35 prettier-autoloads.el
    -rw-r--r-- 18808 07-19 14:35 prettier-el.js
    -rw-r--r--   447 07-19 14:35 prettier-pkg.el
    -rw-r--r-- 51429 07-19 14:45 prettier.el
    -rw-r--r-- 47852 07-19 14:35 prettier.elc
```

but the code was looking for files called `prettier-el.js.gz.base64` and `bootstrap-min.js`.

What has gotten me unblocked is changing to MELPA stable:

```emacs-lisp
(add-to-list 'package-archives
             '("melpa-stable" . "https://stable.melpa.org/packages/") t)
```

**Comment by jscheid** [comment]
Yeah this is quite unfortunate... every day a few dozen people are installing this package, they will all get this error now. I'm not sure what I can do about it, except hope that the MELPA maintainers will take a look soon...

**Comment by jscheid** [comment]
This is fixed now.
