### ISSUE TITLE
make formatting on save optional; note formatting desires to flycheck?

### ISSUE THREAD

**Issue by greg-minshall** [jscheid/prettier.el#98]
**Is your feature request related to a problem? Please describe.**
I'm often frustrated when the code changes the buffer contents underneath me.  for example, i might hit `C-x C-s` in the middle of editing a `for ... {` loop, and then everything below the left bracket get shifted right.

**Describe the solution you'd like**
i would like to be able to turn off automatic re-formatting and, instead, have my formatting mistakes show up via flycheck (say).

**Describe alternatives you've considered**
i guess, either live with it, or disable prettier-mode.

thanks for the tool!

**Comment by m-cat** [comment]
I would also like this -- just a simple variable I could set to disable formatting on save. I have my Emacs save often: whenever the frame loses focus, whenever I run a shell command, etc. -- and as the OP said, it is annoying to have in-progress lines of code get clobbered. I would much rather only have it format when I press `C-c n`.

**Comment by jscheid** [comment]
This is available now, set `prettier-prettify-on-save-flag` via customization or any other way (perhaps buffer-local in a hook.)

I suppose removing the feature and letting user re-add it by setting their own before-save hook would have been more idiomatic, but I don't want to break the existing behavior at this point. Maybe in some future release.

**Comment by m-cat** [comment]
Awesome, thanks!
